from datetime import datetime
import pandas as pd
import streamlit as st
from streamlit_extras.switch_page_button import switch_page

from src.tennis import Match
from src.utils import create_backend_df


# Application page - 'Load Match':
# Let user load a previously created match data csv file and set appropriate session state variables.


if __name__ == "__main__":

    st.set_page_config(
        page_title="Load Match",
        # initial_sidebar_state="collapsed",
    )

    st.title("Analyse a Previous Match")

    with st.container():
        st.header("Upload a File")

        uploaded_file = st.file_uploader(
            "Choose a CSV file",
            type=['csv'],
            accept_multiple_files=False
        )
        if uploaded_file:
            try:
                match_data = pd.read_csv(uploaded_file)
            except:
                st.error("File is not compatible. Please make sure you are uploading a file generated by this application.")
                st.stop()
            temp_backend_df = create_backend_df()
            if match_data.columns.values.shape[0] != temp_backend_df.columns.values.shape[0] \
                    or match_data.columns.values != temp_backend_df.columns.values:
                st.error("File is not compatible. Please make sure you are uploading a file generated by this application.")
                st.stop()

            st.session_state['match_data'] = match_data
            st.session_state['match'] = Match()

            file_name_vs, file_name_dt = uploaded_file.name.split('-')
            st.session_state['player1_name'] = file_name_vs.split('_vs_')[0].replace('_', ' ')
            st.session_state['player2_name'] = file_name_vs.split('_vs_')[1].replace('_', ' ')
            st.session_state['match_datetime'] = datetime.strptime(file_name_dt, '%d%m%Y_%H:%M:%S')

        st.caption("Note that loading a file will overwrite any previous information added in the 'New Match' page.  \nConsider saving the file first.")

    with st.container():
        st.write("###")
        st.divider()
        if st.button("Analyse Match Data"):
            switch_page("Analysis")
